name: Test Actions
run-name: ${{ github.actor }} is testing out GitHub Actions ðŸš€
on: workflow_dispatch
jobs:
  fetch-model:
     runs-on: ubuntu-latest
     steps:
     - run: |
         curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://raw.githubusercontent.com/cess-lab/pi2-auto-detection-dev/main/trained-models/model-98.79%-2023-12-01 18-25.mat
  push-model:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: Andro999b/push@v1.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
